# Generated by Django 3.2.5 on 2021-08-29 01:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pendulum
import shortuuidfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppGroup',
            fields=[
                ('id', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=pendulum.now, editable=False)),
                ('last_updated', models.DateTimeField(default=pendulum.now)),
                ('name', models.TextField(default='UnTitled')),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=pendulum.now, editable=False)),
                ('last_updated', models.DateTimeField(default=pendulum.now)),
                ('name', models.CharField(default='Unknown', max_length=256)),
                ('public_note', models.CharField(blank=True, max_length=256, null=True)),
                ('private_note', models.CharField(blank=True, max_length=256, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=pendulum.now, editable=False)),
                ('last_updated', models.DateTimeField(default=pendulum.now)),
                ('is_admin', models.BooleanField(default=False)),
                ('nick_name', models.CharField(blank=True, max_length=64, null=True)),
                ('app_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.appgroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'app_group')},
            },
        ),
        migrations.AddField(
            model_name='appgroup',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='app_groups', through='project.GroupMember', to=settings.AUTH_USER_MODEL),
        ),
    ]
